site_name: Zettlr Docs
site_url: https://docs.zettlr.com
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: Our comprehensive documentation provides you with everything you need to know about how to make the most of Zettlr.
site_author: Hendrik ERz
copyright: "&copy; 2017-2019 by Zettlr"
docs_dir: docs
site_dir: build
extra_css:
  - assets/app.css
nav:
  - Welcome: index.md
  - Setup: install.md
  - Quick Start: 5-minutes.md
  - Guides:
    - Zettlr as a note taking app: guide-notes.md
    - Zettlr as a Zettelkasten: guide-zettelkasten.md
    - Zettlr as an IDE: guide-ide.md
  - Core:
    - The Editor: editor.md
    - The File List: file-list.md
    - Searching: search.md
    - Exporting: export.md
    - Virtual Directories: virtual-directories.md
    - Custom CSS: custom-css.md
    - Localisation: localisation.md
  - Academic Tools:
    - Citations: citations.md
    - Projects: projects.md
    - Zettelkasten Methods: zkn-method.md
    - Presentations: presentations.md
    - Pomodoro Timer: pomodoro.md
  - References:
    - Shortcuts: shortcuts.md
    - Markdown Basics: markdown-basics.md
    - Settings: settings.md
    - Spell Checking: spell-checking.md
  - Get involved: get-involved.md
  - FAQ: faq.md
theme:
  name: readthedocs
  custom_dir: theme_override
  highlightjs: True
  hljs_languages:
    - javascript
    - css
    - yaml
    - tex
markdown_extensions:
    - toc:
        permalink: True
plugins:
  - search
